[FLASK]
HOST = "0.0.0.0"
PORT = 5042
DEBUG = true

[APP]
PUBLIC_DOMAIN = "http://lf2theo.ddns.net:5566"

[OPENAPI]
BLUEPRINTS = ["view.aaa.bp","view.userCtrl.userctrl","view.fileCtrl.filectrl","view.configCtrl.config_api"]
[[OPENAPI.SERVERS]]
url = "http://localhost:5040"
url1 = "http://localhost:5042"
url2 = "http://lf2theo.ddns.net:5042/api"

[OPENAPI.INFO]
title = "My API"

[DATABASES.default]
SQLALCHEMY_DATABASE_URI = "sqlite:///./ftp/remote_file_access.db"

[DATABASES.log_db]
SQLALCHEMY_DATABASE_URI = "sqlite:///log.db"

[FILE]
path = "./ftp"

[JWT]
JWT_SECRET_KEY = "JWT_KEY"
JWT_ACCESS_TOKEN_EXPIRES = 120