name: Docker Build & Push

on:
  push:
    branches: [ Released ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ Released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 程式碼
        uses: actions/checkout@v4

      - name: 登入 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.backend          # 必須指定
          push: true
          tags: theo1024/remote-file-access-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.frontend         # 必須指定
          push: true
          tags: theo1024/remote-file-access-frontend:latest